### ISSUE TITLE
Autostart problem

### ISSUE THREAD

**Issue by wyq977** [marsqing/libinput-three-finger-drag#10]
Hi thx a lot for this pkg. After quite some research, I found the pkg you build works best for Pop!_OS. 

I just have a small questions about the config, i.e. How to make the lib autostart.

I tried methods below with no luck. Would appreciate if anyone can help!

https://askubuntu.com/questions/1365334/how-to-run-a-process-binary-on-system-startup-reboot-in-ubuntu-20-04-lts
https://askubuntu.com/questions/177837/starting-a-background-application-automatically-on-boot
https://linuxhint.com/use-rc-local-on-ubuntu/

Thx in advance :)

**Comment by marsqing** [comment]
You can try this.
[https://wiki.archlinux.org/title/Autostarting#On_desktop_environment_startup](https://wiki.archlinux.org/title/Autostarting#On_desktop_environment_startup)

**Comment by wyq977** [comment]
Thx for the info. I would take a look and try to add the bin to auto start
