### ISSUE TITLE
How to increase the movement speed?

### ISSUE THREAD

**Issue by fsevenm** [marsqing/libinput-three-finger-drag#5]
I was using Ubuntu 21.04, when I dragged or select using three finger, it was fast. But after upgrade to 21.10 with lot of tools to upgrade including the kernel, when dragging or anything with three finger, it becomes smooth and feels slow.

**Comment by marsqing** [comment]
You can try to adjust the "5.0" in line 48 to a bigger number like 10.0 and rebuild it.
https://github.com/marsqing/libinput-three-finger-drag/blob/099f7708d2dc0ac7620a0371e52cde540dd4f365/src/main.rs#L48

**Comment by fsevenm** [comment]
I tried to increase that "5.0" to "20.0" but the speed didn't change, only the step, that also causes it to become less smooth. As per the logic, that makes sense. What I changed instead, to work around this, is the multiplier.
```rs
xsum += x * 3.0;
ysum += y * 3.0;
```
Also changed the "5.0" to "1.0". Now, it feels smooth and fast. Nice to know this, so later can be easy to configure.

**Comment by shuangye** [comment]
I downloaded the prebuilt release. Running with a command line parameter, e.g., `libinput-three-finger-drag 3`, that does not change the speed.
I then build a binary from source. It worked. Seems you did not update the prebuilt binary. 
Would you please consider updating the binary? Not everyone installed the Rust toolchain.

**Comment by marsqing** [comment]
updated
[v0.2](https://github.com/marsqing/libinput-three-finger-drag/releases/tag/0.2)
